apiVersion: v1
kind: ServiceAccount
metadata:
  name: pods-lister
  namespace: todoapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pods-lister
  namespace: todoapp
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pods-lister-binding
  namespace: todoapp
subjects:
  - kind: ServiceAccount
    name: pods-lister
    namespace: todoapp
roleRef:
  kind: Role
  name: pods-lister
  apiGroup: rbac.authorization.k8s.io
